# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: QUID blog
email: inof@quid.cat
description: >
  Actualitat i entrades al voltat de <strong>QUID</strong>[CONNECTEM EMPRESA I CULTURA]
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.quid.cat" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
assets-images: /assets/images/

name: '<strong>QUID</strong>[CONNECTEM EMPRESA I CULTURA]'
bio: >
  QUID és diàleg és a dir una relació què l’emissor i el receptor intercanvien missatges alternativament.
author_image: "/assets/images/author.png"
twitter_username: quid_CEC
github_username:  freecates

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
