# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: QUID [Connecten Empresa i Cultura]
title-blog: QUID Blog
email: inof@quid.cat
description: >
  Quid és diàleg, és a dir, una relació en què l’emissor i el receptor intercanvien missatges alternativament. Quid és benefici mutu, una estratègia que té com a objectiu que totes les parts surtin beneficiades. Quid és compromís, és a dir, una paraula donada, un benefici acceptat per a la millora.
description-blog: >
  Actualitat i entrades al voltat de <strong>QUID</strong><br/>[CONNECTEM EMPRESA I CULTURA]
title-exits: QUID èxits
description-exits: >
  Casos d'èxit de <strong>QUID</strong><br/>[CONNECTEM EMPRESA I CULTURA]
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.quid.cat" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num/"
assets-images: /assets/images/
assets-videos: /assets/videos/
collections:
  casos-d-exits:
    output: true

name: '<strong>QUID</strong>[CONNECTEM EMPRESA I CULTURA]'
bio: >
  QUID és diàleg és a dir una relació què l’emissor i el receptor intercanvien missatges alternativament.
author_image: "/assets/images/author.png"
twitter_username: quid_CEC
github_username:  freecates
linkedin_page: https://www.linkedin.com/company/programa-quid
address:
  addressLocality: "Sabadell"
  postalCode: "08202"
  streetAddress: "Carrer Sant Francesc, 16"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
